# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZRRrSlSiNRpJuXy-acaYjQ_n2ElPCkG
"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))